import Vue from 'vue'
import {
  Tabbar,
  TabbarItem,
  NavBar,
  SubmitBar,
  Checkbox,
  Search,
  Sticky,
  Swipe,
  SwipeItem,
  Grid,
  GridItem,
  Lazyload,
  Divider,
  PullRefresh,
  List,
  GoodsAction,
  GoodsActionButton,
  GoodsActionIcon,
  Sku,
  Button,
  SwipeCell,
  Card,
  Stepper,
  Empty,
  ActionSheet,
  Form,
  Field,
  Image as VanImage,
  Cell,
  CellGroup,
  Loading,
  Uploader,
  AddressEdit,
  AddressList,
  Icon,
  Tab,
  Tabs,
  Popup,
  Step,
  Steps
} from 'vant'
import 'vant/lib/index.css'

Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(NavBar)
Vue.use(SubmitBar)
Vue.use(Checkbox)
Vue.use(Search)
Vue.use(Sticky)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Lazyload)
Vue.use(Divider)
Vue.use(PullRefresh)
Vue.use(List)
Vue.use(GoodsAction)
Vue.use(GoodsActionButton)
Vue.use(GoodsActionIcon)
Vue.use(Sku)
Vue.use(Button)
Vue.use(SwipeCell)
Vue.use(Card)
Vue.use(Stepper)
Vue.use(Empty)
Vue.use(ActionSheet)
Vue.use(Form)
Vue.use(Field)
Vue.use(VanImage)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(ActionSheet)
Vue.use(Loading)
Vue.use(Uploader)
Vue.use(AddressEdit)
Vue.use(AddressList)
Vue.use(Icon)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Popup)
Vue.use(Step)
Vue.use(Steps)
